### ISSUE TITLE
Error After assembleDebug

### ISSUE THREAD

**Issue by HritikR** [amirk3321/whatsApp_clone#5]
Launching lib/main.dart on CPH1809 in debug mode...
Running Gradle task 'assembleDebug'...
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/country_pickers-1.3.0/lib/utils/my_alert_dialog.dart:139:36: Error: Method not found: 'ButtonTheme.bar'.
      children.add(new ButtonTheme.bar(
                                   ^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/username/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/username/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by HritikR** [comment]
Change dependencies  to  country_pickers: ^2.0.0

**Comment by amirk3321** [comment]
Hi Hritik!
I addressed the bug. I will do update it soon.
